import 'normalize.css/normalize.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/layout/Header";
import Providers from "@/providers";
import { cn } from "@/lib/utils";
import { Footer } from '@/components/layout/Footer';
import Script from "next/script";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        inter.className,
        'relative w-full'
      )}>
        <Providers>
          <main >
            <Header />
            {/* FIXME: fix min height when content is limited and footer is too close to the header and is in the middle of the screen */}
            <div className="my-28 md:mt-32 lg:mt-36 max-w-screen-2xl !mx-auto">
              {children}
            </div>
            <Footer />
          </main>
        </Providers>
      </body>
      <Script src="https://www.googletagmanager.com/gtag/js?id=G-EQXQQ1Z402" />
      <Script id="google-analytics">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
 
          gtag('config', 'G-EQXQQ1Z402');
          `}
      </Script>
    </html>
  );
}
